client:
  inventory:
    base-url: ${INVENTORY_SERVICE_URL:http://inventory-service:8080}
  item:
    base-url: ${ITEM_SERVICE_URL:http://item-service:8080}
  user:
    base-url: ${USER_SERVICE_URL:http://user-service:8080}

spring:
  application:
    name: procurement-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.erp007.xyz/realms/master}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:https://auth.erp007.xyz/realms/master/protocol/openid-connect/certs}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://procurement-postgres:5432/procurement_db}
    username: ${SPRING_DATASOURCE_USERNAME:procurement_user}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /procurement-orders/v3/api-docs
  swagger-ui:
    path: /procurement-orders/swagger-ui.html
