-- 초기 스키마: 상태 변경 이력(history) 테이블 도입 전 상태.
-- purchase_order_lines 의 snapshot 컬럼은 NOT NULL 제약을 가진다(V2에서 제거됨).

CREATE TABLE vendors (
    code           VARCHAR(255) NOT NULL,
    name           VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    phone          VARCHAR(255),
    address        VARCHAR(255),
    active         BOOLEAN      NOT NULL,
    PRIMARY KEY (code)
);

CREATE TABLE po_number_sequences (
    seq_date DATE    NOT NULL,
    last_seq INTEGER NOT NULL,
    PRIMARY KEY (seq_date)
);

CREATE TABLE purchase_orders (
    code                 VARCHAR(255)   NOT NULL,
    vendor_code          VARCHAR(255)   NOT NULL,
    warehouse_code       VARCHAR(255)   NOT NULL,
    status               VARCHAR(255)   NOT NULL,
    desired_arrival_date DATE           NOT NULL,
    memo                 TEXT,
    total_amount         NUMERIC(15, 2) NOT NULL,
    created_by           VARCHAR(255)   NOT NULL,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    approved_by          VARCHAR(255),
    approved_at          TIMESTAMP(6) WITH TIME ZONE,
    received_by          VARCHAR(255),
    received_at          TIMESTAMP(6) WITH TIME ZONE,
    received_date        DATE,
    canceled_by          VARCHAR(255),
    canceled_at          TIMESTAMP(6) WITH TIME ZONE,
    cancel_reason        TEXT,
    PRIMARY KEY (code),
    CONSTRAINT fk_purchase_orders_vendor FOREIGN KEY (vendor_code) REFERENCES vendors (code)
);

CREATE TABLE purchase_order_lines (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    po_number          VARCHAR(255)   NOT NULL,
    item_sku           VARCHAR(255)   NOT NULL,
    item_name_snapshot VARCHAR(255)   NOT NULL,
    unit_snapshot      VARCHAR(255)   NOT NULL,
    order_quantity     INTEGER        NOT NULL,
    unit_price         NUMERIC(15, 2) NOT NULL,
    line_amount        NUMERIC(15, 2) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_purchase_order_lines_po FOREIGN KEY (po_number) REFERENCES purchase_orders (code)
);
