-- 초기 스키마(baseline). 현재 entity 기준 최종 형태로 재작성됨.
-- vendor/warehouse master와의 FK는 끊고 code + 확정 시점 박제명(snapshot)만 보관한다.

-- 공급사 master(검색·DRAFT enrich용 로컬 보관). 발주서와 FK로 묶지 않는다.
CREATE TABLE vendors (
    code           VARCHAR(255) NOT NULL,
    name           VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    phone          VARCHAR(255),
    address        VARCHAR(255),
    active         BOOLEAN      NOT NULL,
    PRIMARY KEY (code)
);

-- 발주 코드 일자별 시퀀스.
CREATE TABLE po_number_sequences (
    seq_date DATE    NOT NULL,
    last_seq INTEGER NOT NULL,
    PRIMARY KEY (seq_date)
);

-- 발주서 애그리거트 루트. vendor/warehouse는 code + 박제명, 상태 부가정보는 이력/staging으로 분리.
CREATE TABLE purchase_orders (
    code                    VARCHAR(255)   NOT NULL,
    vendor_code             VARCHAR(255)   NOT NULL,
    vendor_name_snapshot    VARCHAR(255),
    warehouse_code          VARCHAR(255)   NOT NULL,
    warehouse_name_snapshot VARCHAR(255),
    status                  VARCHAR(255)   NOT NULL,
    memo                    TEXT,
    total_amount            NUMERIC(15, 2) NOT NULL,
    created_by              VARCHAR(255)   NOT NULL,
    created_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version                 BIGINT         NOT NULL DEFAULT 0,
    saga_status             VARCHAR(255)   NOT NULL DEFAULT 'NONE',
    last_failure_reason     TEXT,
    PRIMARY KEY (code)
);

-- 발주 라인. snapshot 컬럼은 nullable(미확정 DRAFT 허용).
CREATE TABLE purchase_order_lines (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    po_number          VARCHAR(255)   NOT NULL,
    item_sku           VARCHAR(255)   NOT NULL,
    item_name_snapshot VARCHAR(255),
    unit_snapshot      VARCHAR(255),
    order_quantity     INTEGER        NOT NULL,
    unit_price         NUMERIC(15, 2) NOT NULL,
    line_amount        NUMERIC(15, 2) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_purchase_order_lines_po FOREIGN KEY (po_number) REFERENCES purchase_orders (code)
);

-- 상태 변경 이력. 확정된 milestone만 적재(provisional 전환은 staging 경유).
CREATE TABLE purchase_order_status_history (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    po_code                 VARCHAR(255) NOT NULL,
    status                  VARCHAR(255) NOT NULL,
    actor_code              VARCHAR(255) NOT NULL,
    actor_name_snapshot     VARCHAR(255),
    actor_position_snapshot VARCHAR(255),
    payload                 JSONB,
    created_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_po_status_history_po_code ON purchase_order_status_history (po_code);

-- saga in-flight 상태 전환 staging. po_code가 PK(애그리거트당 동시 진행 saga 1건).
CREATE TABLE pending_status_change (
    po_code                 VARCHAR(255) NOT NULL,
    status                  VARCHAR(255) NOT NULL,
    actor_code              VARCHAR(255) NOT NULL,
    actor_name_snapshot     VARCHAR(255),
    actor_position_snapshot VARCHAR(255),
    payload                 JSONB,
    occurred_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (po_code)
);

-- 트랜잭셔널 outbox. 비즈니스 트랜잭션과 같은 커밋으로 이벤트를 적재한다.
CREATE TABLE outbox (
    event_id     UUID         NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type   VARCHAR(255) NOT NULL,
    payload      TEXT         NOT NULL,
    status       VARCHAR(255) NOT NULL,
    retry_count  INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (event_id)
);

-- 폴러 조회(status='PENDING' ORDER BY created_at) 대응 인덱스.
CREATE INDEX idx_outbox_status_created_at ON outbox (status, created_at);
