-- 상태 변경 이력 테이블 추가 (ERP-281).

CREATE TABLE purchase_order_status_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    po_code    VARCHAR(255) NOT NULL,
    status     VARCHAR(255) NOT NULL,
    actor_code VARCHAR(255) NOT NULL,
    payload    JSONB,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_po_status_history_po_code ON purchase_order_status_history (po_code);
